### ISSUE TITLE
Feature Request: C64 Port

### ISSUE THREAD

**Issue by starhawk64** [ajbowen249/dungeon-delver-engine#16]
I have a working Commodore 64 (and, soon, possibly a franken-DIY SX-64... sort of, please don't ask) and I'd love to see a port of DDE to that platform.

Please?

**Comment by majick** [comment]
I, too, am a huge C64 fan — I have one on my desk — and would love to see that. However, this engine is written in pure 8080 asm and calls at least some of the features of the m100 ROM directly. "Porting" it would entail essentially writing it all over again from scratch and blank empty files, in 6502 asm, for the C64. A complete reimplementation, not a "port."

If you make any progress reimplementing it yourself I'd love to check it out, though.

**Comment by starhawk64** [comment]
I am by no means a programmer, to the point that there are probably clauses in the Geneva Conventions applicable to keeping me away from anything more advanced than early BASICs for C64, MS-DOS, or the like. I can build hardware, but I absolutely _cannot_ program without committing grievous atrocities, nor can I do so beyond the most simplistic of levels. I can sort of compile Linux drivers as long as "./configure" "make" "sudo make install" is wholly sufficient and throws no errors, and no dependencies are required, but even extraordinarily minimal Arduino "sketches" have a habit of making up their own Wile E Coyote esque cartoon physics sort of ways of failing... much to my predictable befuddlement.

I'm happy to help test, but that's about the limits of my capabilities.

Even more than DDE, I'd love to see a generic "adventure game engine" of some sort. I know that's asking quite a bit, though, which is probably why I've not seen one...

**Comment by majick** [comment]
[ACS](http://crpgaddict.blogspot.com/2015/09/revisiting-adventure-construction.html) is probably the main thing you're looking for as far as "adventure/rpg game engine" for the C64. It's been a good while since I played with it; I probably haven't attempted to make an actual game with the thing since the mid-80s.

It might be worth checking out. Because it's very mature, somewhat well-known software, it's likely there are at least some resources out there to help prospective game-makers with their projects.

**Comment by starhawk64** [comment]
Ooooo... nice! Thank you :3

**Comment by ajbowen249** [comment]
Like `majick` said, C64 would be a complete reimplementation. I do actually own a Commodore 64 and have played around a bit with CC65. I could see a future where a DDE successor written in C could be built for a Model 100 running CP/M with BDS C. But, for now, closing the topic for this repo.
